sudo: 'required'

services:
  - 'docker'
  
language: python
python:
  - 3.5

install:
  - docker build -t avesit/filesender docker/
  - docker run -d -p 127.0.0.1:80:80 --name filesender avesit/filesender
  
script:
  - docker image ls -a
